name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would you use this feature? What problem does it solve?
    validations:
      required: false
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - DNS Records
        - Domain Management
        - Domain Lifecycle
        - Contacts & Privacy
        - SellerHub
        - Personal Nameservers
        - Analysis
        - Other
    validations:
      required: true
